name: Cloud Least Privilege Enforcement

on:
  push:
    paths:
      - "ci/**"
      - "ai/**"
      - "validation/**"
      - ".github/workflows/**"

  pull_request:
    paths:
      - "ci/**"
      - "ai/**"
      - "validation/**"
      - ".github/workflows/**"

jobs:
  least-privilege-check:

    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Python
        shell: cmd
        run: 'C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\python.exe --version'

      - name: Check Ollama
        shell: cmd
        run: ollama --version

      - name: Run Least Privilege CI Pipeline
        shell: cmd
        run: python ci\ci_ai_pipeline.py