name: Test Self Hosted Runner

on:
  push:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Python
        shell: cmd
        run: python --version

      - name: Check Ollama
        shell: cmd
        run: ollama --version